spamlearner:
  restart: always
  image: kvaps/getmail-rspamc
  environment:
    - SERVER=mail.example.org
    - USERNAME=spam@example.org
    - PASSWORD=<password>
    - RSPAMD_HOST=rspamd
    - RSPAMD_PASS=<password>
    - RSPAMD_COMMAND=learn_spam
  links:
    - rspamd:rspamd

hamlearner:
  restart: always
  image: kvaps/getmail-rspamc
  environment:
    - SERVER=mail.example.org
    - USERNAME=ham@example.org
    - PASSWORD=<password>
    - RSPAMD_HOST=rspamd
    - RSPAMD_PASS=<password>
    - RSPAMD_COMMAND=learn_ham
  links:
    - rspamd:rspamd
